name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/torchrunx
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          cache: true
          activate-environment: true
      - run: |
          python -m build
          twine upload dist/*
