name: 'Setup dev environment'
description: ''
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: 0.27.1
        cache: true
        frozen: true
        environments: dev
        activate-environment: dev
