version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.9"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --group docs --frozen
    - uv run -m sphinx -T -j auto -b html -d docs/.doctrees -c docs docs/source $READTHEDOCS_OUTPUT/html
