version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.9"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --group docs --frozen
    - uv run -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: docs/.conf.py
