name: Build and publish docs

on:
  push:
    branches: [update-docs]

jobs:

  publish-docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3.2.2
        with:
          version: "0.5.0"
          python-version-file: ".python-version"
          enable-cache: true
      - run: uv run --only-group docs python -m sphinx --builder html --doctree-dir docs/_build/.doctrees --conf-dir docs --show-traceback docs/source docs/_build/html
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html
      - id: deployment
        uses: actions/deploy-pages@v3
