name: release_to_pypi

on:
  release:
    types: [published]

jobs:
  release-to-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"
      - run: uv build
      - run: uv publish
