name: Setup Dev Environment

on: [workflow_call]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.27.1
          cache: true
          frozen: true
          environments: dev
          activate-environment: dev
